version: '3.8'

services:
  chainflow-app:
    image: node:18-alpine
    container_name: chainflow-app
    working_dir: /app
    volumes:
      - ./app:/app
      - ./.env:/app/.env
      - /app/node_modules
    ports:
      - "8080:8080"
    command: >
      sh -c "npm install &&
             npm run serve -- --skip-lint"
    environment:
      # Essentiels pour le développement
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true  # Activer le polling pour détecter les changements en temps réel
      - ESLINT_NO_DEV_ERRORS=true # Désactiver les erreurs ESLint en dev
      
      # Variables importées directement du fichier .env
      - WALLET_PRIVATE_KEY=${WALLET_PRIVATE_KEY}
      - DEVMODE=${DEVMODE:-true}
      
      # Optimisations de performances pour Node.js
      - NODE_OPTIONS=--max-old-space-size=4096
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
        reservations:
          cpus: '1'
          memory: 2G
    restart: unless-stopped